version: "3"

services:
  rabbitmq:
    image: "rabbitmq:3-management"
    container_name: "rabbitmq-container"
    environment:
      RABBITMQ_ERLANG_COOKIE: "secretcookie"
      RABBITMQ_DEFAULT_USER: "username"
      RABBITMQ_DEFAULT_PASS: "password"
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - rabbitmq-net
    volumes:
      - .rabbitmq_data:/var/lib/rabbitmq

networks:
  rabbitmq-net:
    driver: bridge
